package GUI;

import Category.Category;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class CategoriesView extends JFrame {
    private JPanel contentPane;
    private JList<Category> categoriesJList;
    private JButton addCategoryButton;
    protected RegularTaskManagerView parent;

    public CategoriesView(RegularTaskManagerView parent) {
        this.parent = parent;
        setContentPane(contentPane);
        setTitle("Categories");
        setSize(400, 400);
        setVisible(true);
        updateCategoriesList();
        addCategoryButton.addActionListener(e -> {
            CategoryView categoryView = new CategoryView(this);
        });
        CategoriesView thisView = this;
        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Category selectedCategory = categoriesJList.getSelectedValue();
                    CategoryView categoryView = new CategoryView(thisView, selectedCategory);
                }
            }
        };
        categoriesJList.addMouseListener(mouseListener);
    }

    protected void updateCategoriesList() {
        DefaultListModel<Category> model = new DefaultListModel<Category>();
        for (Category category : parent.taskManager.getCategoryService().getAllCategories()) {
            model.addElement(category);
        }
        categoriesJList.setModel(model);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        categoriesJList = new JList();
        scrollPane1.setViewportView(categoriesJList);
        addCategoryButton = new JButton();
        addCategoryButton.setText("Add Category");
        contentPane.add(addCategoryButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
