package GUI;

import Category.Category;
import Person.Person;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class PersonView extends JFrame {
    private JPanel contentPane;
    private JTextField nameField;
    private JTextField surnameField;
    private JButton cancelButton;
    private JButton confirmButton;
    private JButton deleteButton;
    private PersonsView parent;

    public PersonView(PersonsView parent) {
        contentPane.remove(deleteButton);
        this.parent = parent;
        setContentPane(contentPane);
        setTitle("Add Person");
        setSize(400, 400);
        setVisible(true);
        cancelButton.addActionListener(e -> {
            dispose();
        });
        confirmButton.addActionListener(e -> {
            this.parent.parent.taskManager.getPersonService().addPerson(new Person(nameField.getText(), surnameField.getText()));
            parent.updatePersonsList();
            dispose();
        });
    }

    public PersonView(PersonsView parent, Person selectedPerson) {
        this.parent = parent;
        nameField.setText(selectedPerson.getName());
        surnameField.setText(selectedPerson.getSurname());
        setContentPane(contentPane);
        setTitle("Add Person");
        setSize(400, 400);
        setVisible(true);
        cancelButton.addActionListener(e -> {
            dispose();
        });
        confirmButton.addActionListener(e -> {
            this.parent.parent.taskManager.getPersonService().deletePerson(selectedPerson);
            this.parent.parent.taskManager.getPersonService().addPerson(new Person(nameField.getText(), surnameField.getText()));
            parent.updatePersonsList();
            dispose();
        });
        deleteButton.addActionListener(e -> {
            this.parent.parent.taskManager.getPersonService().deletePerson(selectedPerson);
            parent.updatePersonsList();
            dispose();
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("name");
        contentPane.add(label1, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("surname");
        contentPane.add(label2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameField = new JTextField();
        contentPane.add(nameField, new GridConstraints(0, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        surnameField = new JTextField();
        contentPane.add(surnameField, new GridConstraints(2, 1, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        confirmButton = new JButton();
        confirmButton.setText("confirm");
        contentPane.add(confirmButton, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cancelButton = new JButton();
        cancelButton.setText("cancel");
        contentPane.add(cancelButton, new GridConstraints(3, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("delete");
        contentPane.add(deleteButton, new GridConstraints(3, 3, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
