package GUI;

import Person.Person;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;

public class PersonsView extends JFrame {
    private JPanel contentPane;
    private JButton addPersonButton;
    private JList<Person> personsJList;
    protected RegularTaskManagerView parent;

    public PersonsView(RegularTaskManagerView parent) {
        this.parent = parent;
        setContentPane(contentPane);
        setTitle("Persons");
        setSize(400, 400);
        setVisible(true);
        updatePersonsList();
        addPersonButton.addActionListener(e -> {
            PersonView personView = new PersonView(this);
        });

        PersonsView thisView = this;
        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {
                    Person selectedPerson = personsJList.getSelectedValue();
                    PersonView personView = new PersonView(thisView, selectedPerson);
                }
            }
        };
        personsJList.addMouseListener(mouseListener);
    }

    protected void updatePersonsList() {
        DefaultListModel<Person> model = new DefaultListModel<Person>();
        for (Person person : parent.taskManager.getPersonService().getAllPersons()) {
            model.addElement(person);
        }
        personsJList.setModel(model);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        contentPane.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        personsJList = new JList();
        scrollPane1.setViewportView(personsJList);
        addPersonButton = new JButton();
        addPersonButton.setText("Add Person");
        contentPane.add(addPersonButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
